<?php
/**
 * This file is used to quickly connect to the administration of a WordPress site.
 * It was generated by the WordPress Manager Plugin on cPanel
 * The file can only be used once. It will self delete itself after the first use.
 * -- 
 * Ce fichier est utilisé pour faire une connexion rapide à la page d'administration de WordPress
 * Ce fichier a été généré par l'outil WordPress Manager dans cPanel
 * Ce fichier ne peut être utilisé qu'une fois, après la première utilisation, il s'auto détruit.
 */
 
error_reporting(0);

@unlink(__FILE__);

if(!isset($_REQUEST['pass']) || $_REQUEST['pass'] !== 'Yode9aUlln8zBMaaIkp89I0_JXKDxuntVl57d2PG'){
    die('Accès interdit - Unauthorized Access');
}

if(!file_exists('wp-blog-header.php') || !file_exists('wp-includes/pluggable.php')){
    die('Des fichiers sont manquants - Some files are missing');
}
 
require('wp-blog-header.php');
require('wp-includes/pluggable.php');
$user = get_user_by('ID', 1 );
if ( !is_wp_error( $user ) ) {
    wp_clear_auth_cookie();
    wp_set_current_user ( $user->ID );
    wp_set_auth_cookie  ( $user->ID );
    $redirect_to = user_admin_url();
    wp_safe_redirect( $redirect_to );
    exit();
} else {
    die("L'utilisateur avec l'ID 1 n'existe pas - The user with the ID 1 does not exist");
}